// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lambert_values_cpp
List lambert_values_cpp(NumericVector t, double lambda, double shape);
RcppExport SEXP _lambertReg_lambert_values_cpp(SEXP tSEXP, SEXP lambdaSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(lambert_values_cpp(t, lambda, shape));
    return rcpp_result_gen;
END_RCPP
}
// lambert_cd_cpp
List lambert_cd_cpp(NumericMatrix X, NumericVector y, NumericVector init, double lambda, double shape, int max_sweeps, double kkt_tol, Function pulse);
RcppExport SEXP _lambertReg_lambert_cd_cpp(SEXP XSEXP, SEXP ySEXP, SEXP initSEXP, SEXP lambdaSEXP, SEXP shapeSEXP, SEXP max_sweepsSEXP, SEXP kkt_tolSEXP, SEXP pulseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< int >::type max_sweeps(max_sweepsSEXP);
    Rcpp::traits::input_parameter< double >::type kkt_tol(kkt_tolSEXP);
    Rcpp::traits::input_parameter< Function >::type pulse(pulseSEXP);
    rcpp_result_gen = Rcpp::wrap(lambert_cd_cpp(X, y, init, lambda, shape, max_sweeps, kkt_tol, pulse));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lambertReg_lambert_values_cpp", (DL_FUNC) &_lambertReg_lambert_values_cpp, 3},
    {"_lambertReg_lambert_cd_cpp", (DL_FUNC) &_lambertReg_lambert_cd_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_lambertReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
