# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambert_values_cpp <- function(t, lambda, shape) {
    .Call(`_lambertReg_lambert_values_cpp`, t, lambda, shape)
}

lambert_cd_cpp <- function(X, y, init, lambda, shape, max_sweeps, kkt_tol, pulse) {
    .Call(`_lambertReg_lambert_cd_cpp`, X, y, init, lambda, shape, max_sweeps, kkt_tol, pulse)
}

